services:
  gembib:
    image: gembib
    user: "${UID:-1000}:${GID:-1000}"
    container_name: gembib
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - gembib-network
    volumes:
      - ./:/var/www/html
      # evita problema de permissão (isolado do host)
      - storage_data:/var/www/html/storage
      - cache_data:/var/www/html/bootstrap/cache
    command: >
      bash -c "
        mkdir -p storage bootstrap/cache &&
        chmod -R 775 storage bootstrap/cache
      "

  mariadb:
    image: mariadb:11
    container_name: gembib_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: gembib
      MYSQL_USER: gembib
      MYSQL_PASSWORD: gembib
      MYSQL_ROOT_PASSWORD: gembib
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - gembib-network

networks:
  gembib-network:

volumes:
  mariadb_data:
  storage_data:
  cache_data: